### ISSUE TITLE
NotFound: Page not found

### ISSUE THREAD

**Issue by suprememoocow** [gitterHQ/iframely#1]
This is crashing the embed service

https://app.getsentry.com/gitter/embed/group/51461525/

/var/log/upstart/gitter-embed.log
-- [15-01-29 00:02:08] Loading /iframely for https://gist.github.com/prathameshsnevagi/ce88bff984916584a955
   -- response (by "htmlparser") 404
error: An unexpected error occurred path=/1/iframely, message=Page not found
error: Error: NotFound: Page not found
    at /opt/gitter/gitter-embed/modules/api/views.js:82:33
    at asyncMethodCb (/opt/gitter/gitter-embed/lib/core.js:1125:28)
    at /opt/gitter/gitter-embed/lib/core.js:274:29
    at process._tickDomainCallback (node.js:459:13)
-- [15-01-29 00:02:09] Loading /render for https://gist.github.com/prathameshsnevagi/ce88bff984916584a955
   -- response (by "htmlparser") 404
error: ----------------------------------------------------------------
error: -- A VeryBadThing has happened.
error: ----------------------------------------------------------------
error: Uncaught exceptionTypeError: Cannot read property 'links' of undefined message=Cannot read property 'links' of undefined, name=TypeError
error: TypeError: Cannot read property 'links' of undefined
    at /opt/gitter/gitter-embed/modules/api/views.js:270:56
    at asyncMethodCb (/opt/gitter/gitter-embed/lib/core.js:1125:28)
    at /opt/gitter/gitter-embed/lib/core.js:274:29
    at process._tickDomainCallback (node.js:459:13)
error: Uncaught exceptionTypeError: Cannot read property 'links' of undefined forcing shutdown

**Comment by nleush** [comment]
Following commit https://github.com/itteco/iframely/commit/e122f20d3bcb1e52f3885a0a3b403bf0cabebb05 will fix that error.
